language: node_js
node_js:
  - "6"
sudo: false
cache:
  directories:
    - node_modules
before_script:
  - npm install -g gulp
script: gulp lint && gulp test-ci
after_script: "npm install coveralls@2.10.0 && cat ./coverage/lcov.info | coveralls"
